version: '3.8'

services:
  server:
    build: ./Flask_simple_CRUD
    ports:
      - "5000:5000"
    restart: always
    links:
      - postgres
    depends_on:
      - postgres


  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
      PGDATA: "/var/lib/postgresql/data/pgdata"


    volumes:
      - .:/var/lib/postgresql/data


